name: SmartIrrigate CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:." >> $GITHUB_ENV

      - name: Train and export ONNX model
        run: python app/model_train_and_export.py

      - name: Run unit tests
        run: pytest tests/

      - name: Lint code with flake8
        run: |
          flake8 . \
            --max-line-length=120 \
            --exclude=venv,__pycache__,.git,.github \
            --ignore=E302,E305,E402,W391,W292,F401,F541

      - name: Check Dockerfile syntax
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

      - name: Build Docker image
        run: docker build -t smart-irrigate .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name smart-irrigate smart-irrigate

      - name: Wait for container to be ready
        run: sleep 5

      - name: Cleanup
        if: always()
        run: docker stop smart-irrigate && docker rm smart-irrigate